[admin]
username = "pure"
password = "pure"

[database]
filename = "database.sqlite3"
connections = 2

[github]
username = "PureFunctor"
token = ""

[ssr]
staticUrl = [ "localhost", "static", "index.html" ]
staticPort = 3000

[debug]
serveStatic = true
staticBase = "pf-frontend"
