version: "3.7"

services:

  site-backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    expose:
      - 3000
    volumes:
      - ./app:/app

  site-frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - site-backend
    volumes:
      - ./app/ssl:/etc/ssl:ro

volumes:
  app:
