name: Release Builds

on:
  push:
    branches:
      - stable

jobs:
  docker-builds:
    name: Docker Builds
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create SHA Tag
      id: sha_tag
      run: |
        tag=$(cut -c 1-7 <<< $GITHUB_SHA)
        echo "::set-output name=tag::$tag"

    - name: Install Docker
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
        
    - name: Cache Cabal Directories
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key:
          ${{ hashFiles('pf-backend/purefunctor-me.cabal') }}-${{ steps.sha_tag.outputs.tag }}
        restore-keys: |
          ${{ hashFiles('pf-backend/purefunctor-me.cabal') }}

    - name: Cache Spago Directories
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/spago
          node_modules
        key:
          ${{ hashFiles('pf-frontend/spago.dhall') }}-${{ steps.sha_tag.outputs.tag }}
        restore-keys: |
          ${{ hashFiles('pf-frontend/spago.dhall') }}

    - name: Install Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: "8.10.4"
        cabal-version: "3.4.0.0"

    - name: Install PureScript
      uses: purescript-contrib/setup-purescript@main
      with:
        purescript: "0.13.8"
        spago: "0.19.1"
        zephyr: "0.3.2"

    - name: Build Application (Backend)
      run: |
        cabal update
        cabal install exe:purefunctor-me \
          -O2 \
          --ghc-options=-split-sections \
          --install-method=copy \
          --overwrite-policy=always \
          --installdir=dist-newstyle/bin

    - name: Build Application (Frontend)
      run: |
        yarn && yarn run prod:zephyr

    - name: Create Image (Backend)
      uses: docker/build-push-action@v2
      with:
        context: .
        file: pf-backend/Dockerfile
        push: true
        tags: |
          ghcr.io/purefunctor/site-backend:latest
          ghcr.io/purefunctor/site-backend:${{ steps.sha_tag.outputs.tag }}
        cache-from: type=registry,ref=ghcr.io/purefunctor/site-backend:latest
        cache-to: type=inline

    - name: Create Image (Frontend)
      uses: docker/build-push-action@v2
      with:
        context: .
        file: pf-frontend/Dockerfile
        push: true
        tags: |
          ghcr.io/purefunctor/site-frontend:latest
          ghcr.io/purefunctor/site-frontend:${{ steps.sha_tag.outputs.tag }}
        cache-from: type=registry,ref=ghcr.io/purefunctor/site-frontend:latest
        cache-to: type=inline
