name: Nix Builds

on:

  push:
    branches:
    - develop
    - stable
    - 'feature/**'

    paths:
    - '**.nix'
      
  pull_request:
    branches:
    - develop
    - stable

    paths:
    - '**.nix'

  workflow_dispatch:

jobs:
  build:
    name: Nix Builds
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - name: Install Cachix
      uses: cachix/cachix-action@v8
      with:
        name: ${{ secrets.CACHIX_CACHE_NAME }}
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build Package
      run: nix-build release.nix
