name: Nix Binary Cache

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12
    
    - name: Run Nix
      run: nix-build
    
    - name: Install Cachix
      uses: cachix/cachix-action@v8
      with:
        name: ${{ secrets.CACHIX_CACHE_NAME }}
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
