name: Nix Binary Cache

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Checkout
    - uses: actions/checkout@v2

    - name: Build using Nix
    - uses: cachix/install-nix-action@v12
    - run: nix-build
    
    - name: Store to Cachix
    - uses: cachix/cachix-action@v8
    - with:
        name: ${{ env.CACHIX_CACHE_NAME }}
        authToken: ${{ env.CACHIX_AUTH_TOKEN }}
