name: Nix Builds

on:
  push:
    paths-ignore:
    - '**.md'

  pull_request:
    branches:
    - stable

    paths-ignore:
    - '**.md'

  workflow_dispatch:

jobs:
  nix-builds-backend:
    name: Nix Builds (Backend)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - name: Install Cachix
      uses: cachix/cachix-action@v8
      with:
        name: ${{ secrets.CACHIX_CACHE_NAME }}
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Prepare Cache
      run: |
        tee ~/.config/nix/nix.conf <<EOF
          substituters = https://cache.nixos.org https://hydra.iohk.io https://applicative-labs.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= applicative-labs.cachix.org-1:3v4Z+xR0yJpzaUldL8kkG6ubbSxbXoKZ20NdeGRCnWo=
        EOF

    - name: Build Backend
      run: |
        nix-build -A purefunctor-me.components.exes.purefunctor-me
        du -sh result/bin/purefunctor-me
        ldd result/bin/purefunctor-me
