name: Nix Binary Cache

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Nix
      uses: cachix/install-nix-action@v12
    
    - name: Cachix
      uses: cachix/cachix-action@v8
      with:
        name: ${{ env.CACHIX_CACHE_NAME }}
        authToken: ${{ env.CACHIX_AUTH_TOKEN }}
