name: Haskell Builds

on:
  push:
    paths-ignore:
    - '**.md'

  pull_request:
    branches:
    - stable

    paths-ignore:
    - '**.md'

  workflow_dispatch:

jobs:
  haskell-builds:
    name: Haskell Builds
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create SHA Tag
      id: sha_tag
      run: |
        tag=$(cut -c 1-7 <<< $GITHUB_SHA)
        echo "::set-output name=tag::$tag"

    - name: Install Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: "8.10.3"
        cabal-version: "3.4.0.0"

    - name: Cache Cabal Directories
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key:
          ${{ hashFiles('pf-backend/purefunctor-me.cabal') }}-${{ steps.sha_tag.outputs.tag }}
        restore-keys: |
          ${{ hashFiles('pf-backend/purefunctor-me.cabal') }}

    - name: Build and Test Application
      run: |
        cabal update
        cabal build purefunctor-me
        cabal test purefunctor-me
